class EducationalBackground {
  static Map<String, List<String>> get list => {
        'NA': [],
        'SCHOOLING': ['NA', 'High School', ' 1-7 th class', 'Kinder Garden'],
        'INTERMEDIATE': ['NA', 'MPC', 'BiPC', 'MEC'],
        'POLYTECHNIC / DIPLOMA': [
          'NA',
          'Automobile Engineering',
          'Aeronautical Engineering',
          'Aerospace Engineering',
          'Agriculture Engineering',
          'Art and Craft',
          'Biotechnology Engineering',
          'Computer Science Engineering',
          'Civil Engineering',
          'Chemical Engineering',
          'Ceramic Engineering',
          'Dairy Technology and Engineering',
          'Electronics and communication',
          'Electronics and Telecommunication Engineering',
          'Electrical Engineering',
          'Environmental Engineering',
          'Fashion Designing',
          '1Food Processing Engineering',
          'Genetic Engineering',
          'Interior Decoration',
          'Instrumentation and Control Engineering',
          'Infrastructure Engineering',
          'IT Engineering',
          'Metallurgy Engineering',
          'Motorsport Engineering',
          'Mechanical Engineering',
          'Mining Engineering',
          'Petroleum Engineering',
          'Plastics Engineering',
          'Power Engineering',
          'Production Engineering',
          'Textile Engineering',
          'Others',
        ],
        'BACHELORS': [
          'NA',
          'Automobile Engineering (AUTO)',
          'Aeronautical Engineering (AERO)',
          'Bio Technology Engineering (BTE)',
          'Civil Engineering (CE)',
          'Chemical Engineering (CHEM)',
          'Computer Science and Engineering (CSE)',
          'Electrical and Electronics Engineering (EEE)',
          'Electronics and Communications Engineering (ECE)',
          'Electronics and Instrumentation Engineering (EIE)',
          'Information Technology (IT)',
          'Mechanical Engineering (MECH)',
          'Metallurgical Engineering (MET)',
          'Others',
        ],
        'M.TECH / M.SC': [],
        'MEDICINE': ['NA', 'MBBS', 'OTHERS'],
        'Dental': [],
        'PHARMACY': ['NA', 'B-Pharm', 'M-Pharm'],
        'DEGREE': [
          'NA',
          'B.Com',
          'B.Sc',
          'BBA',
          'Charted Accountants course: CA – CPT & IPCC',
          'BA',
          'LLB',
          'MCA',
          'MBA',
          'Others',
        ],
        'OTHERS': [],
      };
}
